import { useState, useEffect } from "react";
import { useAuth } from "../providers/AuthProvider";
const WORK_TYPES=["Stamped Concrete","Concrete","Masonry","Hardscape","Landscape","Excavation","Drainage","Mixed","Other"];
const CLIENT_STATUSES=["new_lead","estimate_scheduled","estimate_sent","approved","in_progress","completed","lost"];
const SM={new_lead:{label:"New Lead",color:"#8b5cf6"},estimate_scheduled:{label:"Est. Scheduled",color:"#f59e0b"},estimate_sent:{label:"Est. Sent",color:"#3b82f6"},approved:{label:"Approved",color:"#22c55e"},in_progress:{label:"In Progress",color:"#06b6d4"},completed:{label:"Completed",color:"#10b981"},lost:{label:"Lost",color:"#ef4444"}};
const CLIENTS_INIT=[{id:"c1",name:"Mike Rizzo",email:"mike.rizzo@email.com",phone:"(856) 555-0110",address:"142 Oak Lane, Marlton NJ",workType:"Stamped Concrete",status:"in_progress",source:"Google",value:18500,notes:"Patio expansion, Ashlar Slate",estimateDate:null,estimateTime:null,createdAt:"2026-01-28",projectId:"1"},{id:"c2",name:"Sandra DiNapoli",email:"s.dinapoli@email.com",phone:"(856) 555-0111",address:"88 Birch Dr, Cherry Hill NJ",workType:"Concrete",status:"in_progress",source:"Referral",value:24000,notes:"Full driveway tear-out",estimateDate:null,estimateTime:null,createdAt:"2026-02-05",projectId:"2"},{id:"c3",name:"James Whitfield",email:"j.whitfield@email.com",phone:"(856) 555-0201",address:"312 Kings Hwy, Haddonfield NJ",workType:"Masonry",status:"approved",source:"Website",value:32000,notes:"Retaining wall ~80 linear ft",estimateDate:"2026-02-23",estimateTime:"2:00 PM",createdAt:"2026-02-14"},{id:"c4",name:"Lisa Chang",email:"lisa.chang@email.com",phone:"(856) 555-0112",address:"55 Laurel Oak Rd, Voorhees NJ",workType:"Stamped Concrete",status:"in_progress",source:"Google",value:14200,notes:"Pool deck resurface",estimateDate:null,estimateTime:null,createdAt:"2026-01-10",projectId:"4"},{id:"c5",name:"Beth Morrison",email:"beth.m@email.com",phone:"(856) 555-0113",address:"201 Haddon Ave, Collingswood NJ",workType:"Hardscape",status:"completed",source:"Nextdoor",value:9800,notes:"Front walkway Cambridge pavers",estimateDate:null,estimateTime:null,createdAt:"2025-12-20",projectId:"5"},{id:"c6",name:"Tom Klein",email:"tklein@email.com",phone:"(856) 555-0202",address:"77 Fellowship Rd, Mt Laurel NJ",workType:"Hardscape",status:"estimate_scheduled",source:"Referral",value:11500,notes:"Fire pit with seating wall",estimateDate:"2026-02-24",estimateTime:"9:00 AM",createdAt:"2026-02-12"},{id:"c7",name:"Donna Ferraro",email:"dferraro@email.com",phone:"(856) 555-0203",address:"445 Evesham Rd, Voorhees NJ",workType:"Stamped Concrete",status:"new_lead",source:"Phone Call",value:8200,notes:"Stamped overlay ~400sqft",estimateDate:null,estimateTime:null,createdAt:"2026-02-22"},{id:"c8",name:"Ray Chen",email:"rchen@email.com",phone:"(856) 555-0204",address:"19 Maple St, Haddon Twp NJ",workType:"Concrete",status:"lost",source:"Google",value:6800,notes:"Went with cheaper bid",estimateDate:null,estimateTime:null,createdAt:"2026-02-08"},{id:"c9",name:"Angela Russo",email:"arusso@email.com",phone:"(856) 555-0205",address:"602 White Horse Pike, Oaklyn NJ",workType:"Drainage",status:"new_lead",source:"Phone Call",value:null,notes:"French drain consult",estimateDate:null,estimateTime:null,createdAt:"2026-02-23"},{id:"c10",name:"Marcus Johnson",email:"marcus.j@email.com",phone:"(856) 555-0206",address:"88 Tanner St, Haddonfield NJ",workType:"Masonry",status:"estimate_sent",source:"Website",value:15800,notes:"Front steps + veneer columns",estimateDate:null,estimateTime:null,createdAt:"2026-02-18"}];
const PROJECTS=[{id:"1",name:"Rizzo Patio Expansion",client:"Mike Rizzo",address:"142 Oak Lane, Marlton NJ",status:"active",budget:18500,spent:12400,progress:65,tasks:12,tasksDone:8,crew:["Pat B.","Tony M.","Jake R."]},{id:"2",name:"DiNapoli Driveway",client:"Sandra DiNapoli",address:"88 Birch Dr, Cherry Hill NJ",status:"active",budget:24000,spent:8200,progress:30,tasks:18,tasksDone:5,crew:["Pat B.","Chris L."]},{id:"3",name:"Haddonfield Wall",client:"James Whitfield",address:"312 Kings Hwy, Haddonfield NJ",status:"planning",budget:32000,spent:0,progress:0,tasks:22,tasksDone:0,crew:[]},{id:"4",name:"Voorhees Pool Deck",client:"Lisa Chang",address:"55 Laurel Oak Rd, Voorhees NJ",status:"active",budget:14200,spent:11800,progress:85,tasks:10,tasksDone:9,crew:["Tony M.","Jake R."]},{id:"5",name:"Collingswood Walkway",client:"Beth Morrison",address:"201 Haddon Ave, Collingswood NJ",status:"completed",budget:9800,spent:9200,progress:100,tasks:8,tasksDone:8,crew:["Pat B."]},{id:"6",name:"Mt Laurel Fire Pit",client:"Tom Klein",address:"77 Fellowship Rd, Mt Laurel NJ",status:"planning",budget:11500,spent:0,progress:0,tasks:14,tasksDone:0,crew:[]}];
const TEAM=[{id:"1",name:"Pat Breen",role:"owner",email:"pat@breenmasonry.com",phone:"856-555-0101",clockedIn:true,todayHours:6.5,weekHours:34.2,avatar:"PB"},{id:"2",name:"Tony Morales",role:"foreman",email:"tony@breenmasonry.com",phone:"856-555-0102",clockedIn:true,todayHours:7.0,weekHours:38.5,avatar:"TM"},{id:"3",name:"Jake Rivera",role:"worker",email:"jake@breenmasonry.com",phone:"856-555-0103",clockedIn:true,todayHours:6.0,weekHours:36.0,avatar:"JR"},{id:"4",name:"Chris Leone",role:"worker",email:"chris@breenmasonry.com",phone:"856-555-0104",clockedIn:false,todayHours:0,weekHours:28.5,avatar:"CL"},{id:"5",name:"Maria Santos",role:"office",email:"maria@breenmasonry.com",phone:"856-555-0105",clockedIn:true,todayHours:5.5,weekHours:32.0,avatar:"MS"}];
const SCHEDULE=[{id:"1",date:"2026-02-23",time:"7:00 AM",project:"Rizzo Patio",crew:["Pat B.","Tony M.","Jake R."],type:"work",notes:"Stamping day"},{id:"2",date:"2026-02-23",time:"10:00 AM",project:"DiNapoli Driveway",crew:["Chris L."],type:"work",notes:"Form setup"},{id:"3",date:"2026-02-23",time:"2:00 PM",project:"Haddonfield Wall",crew:[],type:"estimate",notes:"Site visit"},{id:"4",date:"2026-02-24",time:"7:30 AM",project:"Voorhees Pool Deck",crew:["Tony M.","Jake R."],type:"work",notes:"Seal coat"},{id:"5",date:"2026-02-24",time:"9:00 AM",project:"Mt Laurel Fire Pit",crew:[],type:"estimate",notes:"Measurements"},{id:"6",date:"2026-02-25",time:"7:00 AM",project:"Rizzo Patio",crew:["Pat B.","Tony M.","Jake R.","Chris L."],type:"work",notes:"Color hardener"}];
const INVOICES=[{id:"INV-0042",project:"Collingswood Walkway",client:"Beth Morrison",amount:9800,paid:9800,status:"paid",date:"2026-02-12",dueDate:"2026-02-26"},{id:"INV-0043",project:"Voorhees Pool Deck",client:"Lisa Chang",amount:14200,paid:7100,status:"sent",date:"2026-02-20",dueDate:"2026-03-06"},{id:"INV-0044",project:"Rizzo Patio",client:"Mike Rizzo",amount:18500,paid:9250,status:"sent",date:"2026-02-18",dueDate:"2026-03-04"},{id:"INV-0045",project:"DiNapoli Driveway",client:"Sandra DiNapoli",amount:24000,paid:0,status:"draft",date:"2026-02-22",dueDate:null}];
const EQUIPMENT=[{id:"1",name:"Honda Power Trowel",serial:"PT-2019-A",status:"checked_out",project:"Rizzo Patio",checkedBy:"Tony M."},{id:"2",name:"Stihl Concrete Saw",serial:"CS-2021-B",status:"available",project:null,checkedBy:null},{id:"3",name:"Wacker Compactor",serial:"PC-2020-C",status:"checked_out",project:"DiNapoli",checkedBy:"Chris L."},{id:"4",name:"DeWalt Hammer Drill",serial:"HD-2022-D",status:"available",project:null,checkedBy:null},{id:"5",name:"Kushlan 600DD Mixer",serial:"MX-2018-E",status:"maintenance",project:null,checkedBy:null},{id:"6",name:"Marshalltown Fresno 48\"",serial:"FT-2023-F",status:"checked_out",project:"Rizzo Patio",checkedBy:"Pat B."},{id:"7",name:"Bosch Laser Level",serial:"RL-2021-G",status:"available",project:null,checkedBy:null}];
const ACTIVITY=[{id:"1",a:"Tony M.",b:"Clocked in",c:"Rizzo Patio",t:"6:45 AM",i:"⏰"},{id:"2",a:"Pat B.",b:"Clocked in",c:"Rizzo Patio",t:"6:50 AM",i:"⏰"},{id:"3",a:"Jake R.",b:"Completed task",c:"Expansion joints",t:"9:22 AM",i:"✅"},{id:"4",a:"Maria S.",b:"Sent invoice",c:"INV-0043",t:"10:15 AM",i:"📄"},{id:"5",a:"System",b:"New lead",c:"Donna Ferraro",t:"4:12 PM",i:"📞"}];
const TIME_ENTRIES=[{id:"1",emp:"Pat Breen",date:"2026-02-23",ci:"6:50 AM",co:null,hrs:6.5,proj:"Rizzo Patio"},{id:"2",emp:"Tony Morales",date:"2026-02-23",ci:"6:45 AM",co:null,hrs:7.0,proj:"Rizzo Patio"},{id:"3",emp:"Jake Rivera",date:"2026-02-23",ci:"7:00 AM",co:null,hrs:6.0,proj:"Rizzo Patio"},{id:"4",emp:"Chris Leone",date:"2026-02-22",ci:"7:15 AM",co:"3:45 PM",hrs:8.5,proj:"DiNapoli"},{id:"5",emp:"Maria Santos",date:"2026-02-23",ci:"8:30 AM",co:null,hrs:5.5,proj:"Office"}];
const INTEGRATIONS_INIT=[{provider:"stripe",name:"Stripe",icon:"💳",color:"#635BFF",connected:true,acct:"Breen Masonry LLC",desc:"Card payments & auto pay links on invoices"},{provider:"square",name:"Square",icon:"⬜",color:"#00D632",connected:false,acct:null,desc:"In-person & online payments via Square"},{provider:"quickbooks",name:"QuickBooks",icon:"📗",color:"#2CA01C",connected:true,acct:"Breen Masonry & Concrete",desc:"Sync invoices, expenses, client data"}];
const $=n=>n==null?"—":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",minimumFractionDigits:0}).format(n);
const stC={active:"#22c55e",planning:"#f59e0b",completed:"#3b82f6"};const invC={paid:"#22c55e",sent:"#3b82f6",draft:"#8899aa",overdue:"#ef4444"};const eqC={available:"#22c55e",checked_out:"#f59e0b",maintenance:"#ef4444"};
const NAV=[{id:"dashboard",label:"Dashboard",ic:"◻"},{id:"clients",label:"Clients",ic:"👤"},{id:"projects",label:"Projects",ic:"📁"},{id:"schedule",label:"Schedule",ic:"📅"},{id:"invoices",label:"Invoices",ic:"💰"},{id:"hours",label:"Hours",ic:"⏱"},{id:"equipment",label:"Equipment",ic:"🔧"},{id:"team",label:"Team",ic:"👥"},{id:"integrations",label:"Integrations",ic:"🔗"}];
const Bg=({l,c})=><span style={{fontSize:11,fontWeight:700,textTransform:"uppercase",letterSpacing:.3,color:c,padding:"3px 10px",borderRadius:5,background:c+"18",whiteSpace:"nowrap"}}>{l}</span>;
const Pl=({a,onClick,l,c})=><button onClick={onClick} style={{padding:"5px 10px",borderRadius:6,border:"1px solid",borderColor:a?(c||"#c41e1e")+"60":"#2a3a4a",background:a?(c||"#c41e1e")+"15":"transparent",color:a?(c||"#e63939"):"#586878",fontWeight:600,fontSize:11,cursor:"pointer",fontFamily:"inherit",whiteSpace:"nowrap"}}>{l}</button>;
function Cd({children,style,hover,onClick}){const[h,setH]=useState(false);return<div onClick={onClick} onMouseEnter={()=>hover&&setH(true)} onMouseLeave={()=>hover&&setH(false)} style={{background:"#1c2a38",borderRadius:14,border:"1px solid #2a3a4a",padding:20,transition:"all .15s ease",...(hover&&h?{borderColor:"#3a4a5a",transform:"translateY(-1px)",boxShadow:"0 4px 20px rgba(0,0,0,.25)"}:{}),...style}}>{children}</div>}
function SB({label,value,sub,color,icon}){return<Cd hover style={{flex:1,minWidth:150}}><div style={{display:"flex",alignItems:"flex-start",justifyContent:"space-between"}}><div><div style={{fontSize:11,fontWeight:700,color:"#8899aa",textTransform:"uppercase",letterSpacing:.8}}>{label}</div><div style={{fontSize:26,fontWeight:800,color:"#e8ecf1",marginTop:6,letterSpacing:-.5}}>{value}</div>{sub&&<div style={{fontSize:12,color:color||"#586878",fontWeight:600,marginTop:4}}>{sub}</div>}</div><div style={{width:38,height:38,borderRadius:11,background:(color||"#c41e1e")+"18",display:"flex",alignItems:"center",justifyContent:"center",fontSize:17}}>{icon}</div></div></Cd>}
const cI={width:"100%",padding:"6px 8px",borderRadius:6,border:"1px solid #2a3a4a",background:"#1c2a38",color:"#e8ecf1",fontSize:13,fontFamily:"inherit",outline:"none",boxSizing:"border-box"};
const pI={width:"100%",padding:"9px 12px",borderRadius:8,border:"1px solid #2a3a4a",background:"#0f1419",color:"#e8ecf1",fontSize:13,fontFamily:"inherit",outline:"none",boxSizing:"border-box"};

export default function Dashboard(){
  const { user, profile, company, signOut } = useAuth();
  const[nav,setNav]=useState("clients");const[col,setCol]=useState(false);const[rdy,setRdy]=useState(false);
  const[clients,setClients]=useState(CLIENTS_INIT);const[ints,setInts]=useState(INTEGRATIONS_INIT);
  useEffect(()=>{setRdy(true)},[]);
  return(<div style={{display:"flex",height:"100vh",width:"100%",fontFamily:"'DM Sans',sans-serif",background:"#0f1419",color:"#e8ecf1",opacity:rdy?1:0,transition:"opacity .4s",overflow:"hidden"}}>
    
    <div style={{width:col?64:220,minWidth:col?64:220,background:"#141d26",borderRight:"1px solid #1e2d3d",display:"flex",flexDirection:"column",transition:"all .2s cubic-bezier(.4,0,.2,1)"}}>
      <div style={{padding:col?"14px 8px":"14px 14px",borderBottom:"1px solid #1e2d3d",display:"flex",alignItems:"center",gap:10,cursor:"pointer"}} onClick={()=>setCol(!col)}>
        <img src="/logo.png" alt="Form Up" style={{width:36,height:36,borderRadius:9,objectFit:"cover",flexShrink:0}}/>
        {!col&&<div><div style={{fontSize:15,fontWeight:800,letterSpacing:-.5,color:"#fff"}}>Form Up</div><div style={{fontSize:10,color:"#586878"}}>Office Dashboard</div></div>}
      </div>
      <div style={{flex:1,padding:"10px 6px",display:"flex",flexDirection:"column",gap:1}}>
        {NAV.map(n=>{const a=nav===n.id;return<button key={n.id} onClick={()=>setNav(n.id)} style={{display:"flex",alignItems:"center",gap:10,padding:col?"9px 10px":"9px 12px",borderRadius:8,border:"none",cursor:"pointer",background:a?"rgba(196,30,30,.12)":"transparent",color:a?"#e63939":"#8899aa",fontSize:13,fontWeight:a?700:500,fontFamily:"inherit",justifyContent:col?"center":"flex-start",position:"relative"}} onMouseEnter={e=>{if(!a)e.currentTarget.style.background="rgba(255,255,255,.03)"}} onMouseLeave={e=>{if(!a)e.currentTarget.style.background="transparent"}}>{a&&<div style={{position:"absolute",left:0,top:"50%",transform:"translateY(-50%)",width:3,height:18,borderRadius:2,background:"#c41e1e"}}/>}<span style={{fontSize:15,width:22,textAlign:"center"}}>{n.ic}</span>{!col&&<span>{n.label}</span>}</button>})}
      </div>
      <div style={{padding:col?"14px 8px":"14px 14px",borderTop:"1px solid #1e2d3d",display:"flex",alignItems:"center",gap:10,justifyContent:col?"center":"flex-start"}}>
        <div style={{width:32,height:32,borderRadius:9,background:"linear-gradient(135deg,#c41e1e,#e63939)",display:"flex",alignItems:"center",justifyContent:"center",fontWeight:700,fontSize:12,color:"#fff"}}>PB</div>
        {!col&&<div><div style={{fontSize:12,fontWeight:700}}>{profile?.full_name || user?.email?.split("@")[0] || "User"}</div><div style={{fontSize:10,color:"#586878",cursor:"pointer"}} onClick={signOut}>Sign Out</div></div>}
      </div>
    </div>
    <div style={{flex:1,display:"flex",flexDirection:"column",overflow:"hidden"}}>
      <div style={{height:56,minHeight:56,background:"#141d26",borderBottom:"1px solid #1e2d3d",display:"flex",alignItems:"center",justifyContent:"space-between",padding:"0 24px"}}>
        <div style={{display:"flex",alignItems:"center",gap:12}}><span style={{fontSize:17,fontWeight:800}}>{NAV.find(n=>n.id===nav)?.label}</span><span style={{fontSize:12,color:"#586878"}}>Mon, Feb 23, 2026</span></div>
        <div style={{display:"flex",gap:10}}><button onClick={()=>setNav("invoices")} style={{padding:"7px 14px",borderRadius:8,background:"linear-gradient(135deg,#c41e1e,#e63939)",border:"none",color:"#fff",fontWeight:700,fontSize:12,cursor:"pointer",fontFamily:"inherit"}}>+ New Invoice</button><div style={{width:34,height:34,borderRadius:9,background:"#1c2a38",border:"1px solid #2a3a4a",display:"flex",alignItems:"center",justifyContent:"center",cursor:"pointer",fontSize:15}}>🔔</div></div>
      </div>
      <div style={{flex:1,overflow:"auto",padding:nav==="clients"?0:24,background:"#0f1419"}}>
        {nav==="dashboard"&&<DashView/>}{nav==="clients"&&<ClientsView c={clients} sc={setClients}/>}{nav==="projects"&&<ProjView/>}{nav==="schedule"&&<SchedView/>}{nav==="invoices"&&<InvView/>}{nav==="hours"&&<HrsView/>}{nav==="equipment"&&<EqView/>}{nav==="team"&&<TeamView/>}{nav==="integrations"&&<IntView ints={ints} si={setInts}/>}
      </div>
    </div>
  </div>);
}

function ClientsView({c:clients,sc:setClients}){
  const[selId,setSelId]=useState(null);const[srch,setSrch]=useState("");const[sf,setSf]=useState("all");const[showAdd,setShowAdd]=useState(false);
  const[nc,setNc]=useState({name:"",email:"",phone:"",address:"",workType:"Stamped Concrete",notes:""});const[sC,setSC]=useState(null);const[sD,setSD]=useState("asc");
  const sel=clients.find(x=>x.id===selId);const cts={};CLIENT_STATUSES.forEach(s=>{cts[s]=clients.filter(x=>x.status===s).length});
  const fil=clients.filter(x=>{if(sf!=="all"&&x.status!==sf)return false;if(srch){const q=srch.toLowerCase();return x.name.toLowerCase().includes(q)||x.address.toLowerCase().includes(q)||x.workType.toLowerCase().includes(q)}return true});
  const sorted=[...fil].sort((a,b)=>{if(!sC)return 0;let av=a[sC],bv=b[sC];if(av==null)return 1;if(bv==null)return-1;if(typeof av==="string")av=av.toLowerCase();if(typeof bv==="string")bv=bv.toLowerCase();return av<bv?(sD==="asc"?-1:1):av>bv?(sD==="asc"?1:-1):0});
  const doSort=k=>{if(sC===k)setSD(d=>d==="asc"?"desc":"asc");else{setSC(k);setSD("asc")}};
  const addC=()=>{if(!nc.name.trim())return;setClients(p=>[...p,{...nc,id:"c"+Date.now(),status:"new_lead",source:"Manual",value:null,estimateDate:null,estimateTime:null,createdAt:"2026-02-23"}]);setNc({name:"",email:"",phone:"",address:"",workType:"Stamped Concrete",notes:""});setShowAdd(false)};
  const upC=(id,u)=>setClients(p=>p.map(x=>x.id===id?{...x,...u}:x));
  const COLS=[{k:"name",l:"Client",w:"18%"},{k:"phone",l:"Phone",w:"11%"},{k:"address",l:"Address",w:"17%"},{k:"workType",l:"Work Type",w:"11%"},{k:"status",l:"Status",w:"12%"},{k:"value",l:"Value",w:"9%"},{k:"estimateDate",l:"Estimate",w:"12%"},{k:"createdAt",l:"Created",w:"8%"}];
  return(<div style={{display:"flex",height:"100%",overflow:"hidden"}}>
    <div style={{flex:1,display:"flex",flexDirection:"column",overflow:"hidden"}}>
      <div style={{padding:"12px 24px",borderBottom:"1px solid #1e2d3d",background:"#141d26",display:"flex",alignItems:"center",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}>
        <div style={{display:"flex",alignItems:"center",gap:8,flex:1,minWidth:200}}>
          <div style={{position:"relative",flex:1,maxWidth:280}}><input value={srch} onChange={e=>setSrch(e.target.value)} placeholder="🔍 Search clients..." style={{width:"100%",padding:"7px 10px",borderRadius:7,border:"1px solid #2a3a4a",background:"#1c2a38",color:"#e8ecf1",fontSize:13,fontFamily:"inherit",outline:"none",boxSizing:"border-box"}}/></div>
          <div style={{display:"flex",gap:4,flexWrap:"wrap"}}><Pl a={sf==="all"} onClick={()=>setSf("all")} l={"All ("+clients.length+")"}/>{CLIENT_STATUSES.filter(s=>cts[s]>0).map(s=><Pl key={s} a={sf===s} onClick={()=>setSf(s)} l={SM[s].label+" ("+cts[s]+")"} c={SM[s].color}/>)}</div>
        </div>
        <button onClick={()=>setShowAdd(true)} style={{padding:"8px 16px",borderRadius:8,background:"linear-gradient(135deg,#c41e1e,#e63939)",border:"none",color:"#fff",fontWeight:700,fontSize:13,cursor:"pointer",fontFamily:"inherit"}}>+ New Client</button>
      </div>
      <div style={{padding:"6px 24px",background:"#0f1419",borderBottom:"1px solid #1e2d3d",display:"flex",gap:3}}>{CLIENT_STATUSES.map(s=>{const ct=cts[s];if(!ct)return null;return<div key={s} title={SM[s].label+": "+ct} style={{height:5,borderRadius:3,flex:(ct/clients.length)*100,background:SM[s].color,opacity:.7}}/>})}</div>
      <div style={{flex:1,overflow:"auto"}}>
        <table style={{width:"100%",borderCollapse:"collapse",fontSize:13,minWidth:900}}>
          <thead><tr style={{position:"sticky",top:0,background:"#141d26",zIndex:2}}>{COLS.map(c=><th key={c.k} onClick={()=>doSort(c.k)} style={{textAlign:"left",padding:"10px 14px",fontSize:10,fontWeight:700,color:sC===c.k?"#e63939":"#586878",textTransform:"uppercase",letterSpacing:.5,cursor:"pointer",width:c.w,userSelect:"none",borderBottom:"2px solid #1e2d3d"}}>{c.l}{sC===c.k&&<span style={{marginLeft:4,fontSize:9}}>{sD==="asc"?"▲":"▼"}</span>}</th>)}</tr></thead>
          <tbody>
            {showAdd&&<tr style={{background:"#c41e1e08",borderBottom:"1px solid #c41e1e30"}}><td style={{padding:"8px 14px"}}><input value={nc.name} onChange={e=>setNc(p=>({...p,name:e.target.value}))} placeholder="Client name..." autoFocus style={{...cI,fontWeight:700}} onKeyDown={e=>e.key==="Enter"&&addC()}/></td><td style={{padding:"8px 14px"}}><input value={nc.phone} onChange={e=>setNc(p=>({...p,phone:e.target.value}))} placeholder="(856) 555-..." style={cI}/></td><td style={{padding:"8px 14px"}}><input value={nc.address} onChange={e=>setNc(p=>({...p,address:e.target.value}))} placeholder="123 Main St" style={cI}/></td><td style={{padding:"8px 14px"}}><select value={nc.workType} onChange={e=>setNc(p=>({...p,workType:e.target.value}))} style={{...cI,cursor:"pointer"}}>{WORK_TYPES.map(w=><option key={w}>{w}</option>)}</select></td><td style={{padding:"8px 14px"}}><Bg l="New Lead" c="#8b5cf6"/></td><td colSpan={3} style={{padding:"8px"}}><div style={{display:"flex",gap:4}}><button onClick={addC} style={{padding:"4px 12px",borderRadius:6,border:"none",background:"#22c55e",color:"#fff",cursor:"pointer",fontSize:12,fontWeight:700}}>Add</button><button onClick={()=>setShowAdd(false)} style={{padding:"4px 12px",borderRadius:6,border:"none",background:"#2a3a4a",color:"#8899aa",cursor:"pointer",fontSize:12}}>✕</button></div></td></tr>}
            {sorted.map(c=>{const sm=SM[c.status];const is=selId===c.id;return<tr key={c.id} onClick={()=>setSelId(is?null:c.id)} style={{borderBottom:"1px solid #1e2d3d",cursor:"pointer",background:is?"#c41e1e0a":"transparent",borderLeft:is?"3px solid #c41e1e":"3px solid transparent"}} onMouseEnter={e=>{if(!is)e.currentTarget.style.background="#ffffff04"}} onMouseLeave={e=>{if(!is)e.currentTarget.style.background="transparent"}}><td style={{padding:"11px 14px"}}><div style={{display:"flex",alignItems:"center",gap:10}}><div style={{width:30,height:30,borderRadius:8,background:sm.color+"20",border:"1.5px solid "+sm.color+"40",display:"flex",alignItems:"center",justifyContent:"center",fontSize:11,fontWeight:700,color:sm.color}}>{c.name.split(" ").map(n=>n[0]).join("").slice(0,2)}</div><div><div style={{fontWeight:700,fontSize:13}}>{c.name}</div>{c.email&&<div style={{fontSize:11,color:"#586878"}}>{c.email}</div>}</div></div></td><td style={{padding:"11px 14px",color:"#8899aa",fontFamily:"'Space Mono',monospace",fontSize:12}}>{c.phone}</td><td style={{padding:"11px 14px",color:"#8899aa",fontSize:12}}>{c.address}</td><td style={{padding:"11px 14px"}}><span style={{fontSize:11,fontWeight:600,background:"#23323f",color:"#8899aa",padding:"3px 8px",borderRadius:5}}>{c.workType}</span></td><td style={{padding:"11px 14px"}}><Bg l={sm.label} c={sm.color}/></td><td style={{padding:"11px 14px",fontWeight:700,color:c.value?"#e8ecf1":"#586878"}}>{$(c.value)}</td><td style={{padding:"11px 14px"}}>{c.estimateDate?<div><div style={{fontSize:12,fontWeight:600,color:"#f59e0b"}}>📅 {c.estimateDate}</div>{c.estimateTime&&<div style={{fontSize:11,color:"#586878"}}>{c.estimateTime}</div>}</div>:<span style={{color:"#586878"}}>—</span>}</td><td style={{padding:"11px 14px",fontSize:12,color:"#586878"}}>{c.createdAt}</td></tr>})}
          </tbody>
        </table>
      </div>
    </div>
    <div style={{width:sel?420:0,minWidth:sel?420:0,background:"#141d26",borderLeft:sel?"1px solid #1e2d3d":"none",overflow:"hidden",transition:"all .25s cubic-bezier(.4,0,.2,1)"}}>{sel&&<CPanel c={sel} up={u=>upC(sel.id,u)} close={()=>setSelId(null)}/>}</div>
  </div>);
}

function CPanel({c,up,close}){
  const[ed,setEd]=useState(false);const[f,setF]=useState(c);const[ss,setSs]=useState(false);const[eD,setED]=useState(c.estimateDate||"");const[eT,setET]=useState(c.estimateTime||"");
  useEffect(()=>{setF(c);setED(c.estimateDate||"");setET(c.estimateTime||"");setEd(false);setSs(false)},[c.id]);
  const sv=()=>{up({name:f.name,email:f.email,phone:f.phone,address:f.address,workType:f.workType,notes:f.notes,value:f.value});setEd(false)};
  const se=()=>{if(!eD)return;up({estimateDate:eD,estimateTime:eT||null,status:c.status==="new_lead"?"estimate_scheduled":c.status});setSs(false)};
  const sm=SM[c.status];
  return(<div style={{height:"100%",display:"flex",flexDirection:"column",overflow:"hidden"}}>
    <div style={{padding:"16px 20px",borderBottom:"1px solid #1e2d3d",display:"flex",alignItems:"center",justifyContent:"space-between"}}><div style={{display:"flex",alignItems:"center",gap:10}}><div style={{width:38,height:38,borderRadius:10,background:"linear-gradient(135deg,"+sm.color+"40,"+sm.color+"20)",border:"2px solid "+sm.color+"50",display:"flex",alignItems:"center",justifyContent:"center",fontSize:14,fontWeight:800,color:sm.color}}>{c.name.split(" ").map(n=>n[0]).join("").slice(0,2)}</div><div><div style={{fontSize:16,fontWeight:800}}>{c.name}</div><Bg l={sm.label} c={sm.color}/></div></div><button onClick={close} style={{width:30,height:30,borderRadius:7,background:"#1c2a38",border:"1px solid #2a3a4a",color:"#8899aa",cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"center",fontSize:14}}>✕</button></div>
    <div style={{flex:1,overflow:"auto",padding:20}}>
      <div style={{display:"flex",gap:8,marginBottom:20}}><button onClick={()=>setSs(true)} style={{flex:1,padding:"10px",borderRadius:9,background:"linear-gradient(135deg,#f59e0b,#d97706)",border:"none",color:"#fff",fontWeight:700,fontSize:12,cursor:"pointer",fontFamily:"inherit"}}>📅 Schedule Estimate</button><button onClick={()=>setEd(true)} style={{flex:1,padding:"10px",borderRadius:9,background:"#1c2a38",border:"1px solid #2a3a4a",color:"#8899aa",fontWeight:700,fontSize:12,cursor:"pointer",fontFamily:"inherit"}}>✏️ Edit</button></div>
      {ss&&<div style={{background:"#1c2a38",borderRadius:12,padding:16,marginBottom:16,border:"1px solid #f59e0b30"}}><div style={{fontSize:14,fontWeight:700,marginBottom:12,color:"#f59e0b"}}>📅 Schedule Estimate</div><div style={{marginBottom:10}}><label style={{fontSize:11,fontWeight:700,color:"#586878",display:"block",marginBottom:4}}>DATE</label><input type="date" value={eD} onChange={e=>setED(e.target.value)} style={{...pI,colorScheme:"dark"}}/></div><div style={{marginBottom:14}}><label style={{fontSize:11,fontWeight:700,color:"#586878",display:"block",marginBottom:4}}>TIME</label><input type="time" value={eT} onChange={e=>setET(e.target.value)} style={{...pI,colorScheme:"dark"}}/></div><div style={{display:"flex",gap:8}}><button onClick={se} disabled={!eD} style={{flex:1,padding:"9px",borderRadius:8,background:eD?"#f59e0b":"#f59e0b50",border:"none",color:"#fff",fontWeight:700,fontSize:13,cursor:eD?"pointer":"not-allowed",fontFamily:"inherit"}}>Confirm</button><button onClick={()=>setSs(false)} style={{flex:1,padding:"9px",borderRadius:8,background:"#23323f",border:"none",color:"#8899aa",fontWeight:600,fontSize:13,cursor:"pointer",fontFamily:"inherit"}}>Cancel</button></div></div>}
      <div style={{marginBottom:20}}><div style={{fontSize:11,fontWeight:700,color:"#586878",marginBottom:8,textTransform:"uppercase"}}>Pipeline Stage</div><div style={{display:"flex",gap:4,flexWrap:"wrap"}}>{CLIENT_STATUSES.map(s=>{const m=SM[s];const a=c.status===s;return<button key={s} onClick={()=>up({status:s})} style={{padding:"5px 10px",borderRadius:6,border:"1px solid",borderColor:a?m.color+"60":"#2a3a4a",background:a?m.color+"18":"transparent",color:a?m.color:"#586878",fontWeight:a?700:500,fontSize:11,cursor:"pointer",fontFamily:"inherit"}}>{m.label}</button>})}</div></div>
      {ed?<div style={{display:"flex",flexDirection:"column",gap:12}}>{[{k:"name",l:"Name"},{k:"email",l:"Email"},{k:"phone",l:"Phone"},{k:"address",l:"Address"}].map(x=><div key={x.k}><label style={{fontSize:11,fontWeight:700,color:"#586878",display:"block",marginBottom:4,textTransform:"uppercase"}}>{x.l}</label><input value={f[x.k]||""} onChange={e=>setF(p=>({...p,[x.k]:e.target.value}))} style={pI}/></div>)}<div><label style={{fontSize:11,fontWeight:700,color:"#586878",display:"block",marginBottom:4,textTransform:"uppercase"}}>Work Type</label><select value={f.workType} onChange={e=>setF(p=>({...p,workType:e.target.value}))} style={{...pI,cursor:"pointer"}}>{WORK_TYPES.map(w=><option key={w}>{w}</option>)}</select></div><div><label style={{fontSize:11,fontWeight:700,color:"#586878",display:"block",marginBottom:4,textTransform:"uppercase"}}>Value ($)</label><input type="number" value={f.value||""} onChange={e=>setF(p=>({...p,value:e.target.value?+e.target.value:null}))} style={pI}/></div><div><label style={{fontSize:11,fontWeight:700,color:"#586878",display:"block",marginBottom:4,textTransform:"uppercase"}}>Notes</label><textarea value={f.notes||""} onChange={e=>setF(p=>({...p,notes:e.target.value}))} rows={3} style={{...pI,resize:"vertical"}}/></div><div style={{display:"flex",gap:8}}><button onClick={sv} style={{flex:1,padding:"10px",borderRadius:8,background:"#c41e1e",border:"none",color:"#fff",fontWeight:700,cursor:"pointer",fontFamily:"inherit"}}>Save</button><button onClick={()=>setEd(false)} style={{flex:1,padding:"10px",borderRadius:8,background:"#23323f",border:"none",color:"#8899aa",cursor:"pointer",fontFamily:"inherit"}}>Cancel</button></div></div>:<div style={{display:"flex",flexDirection:"column",gap:14}}>{[{i:"📧",l:"Email",v:c.email},{i:"📞",l:"Phone",v:c.phone},{i:"📍",l:"Address",v:c.address},{i:"🔨",l:"Work Type",v:c.workType},{i:"💰",l:"Value",v:c.value?$(c.value):"Not set"},{i:"📋",l:"Source",v:c.source}].map((r,i)=><div key={i} style={{display:"flex",gap:10}}><span style={{fontSize:14}}>{r.i}</span><div><div style={{fontSize:11,color:"#586878"}}>{r.l}</div><div style={{fontSize:13,fontWeight:600}}>{r.v||"—"}</div></div></div>)}{c.estimateDate&&<div style={{display:"flex",gap:10}}><span>📅</span><div><div style={{fontSize:11,color:"#586878"}}>Estimate</div><div style={{fontSize:13,fontWeight:600,color:"#f59e0b"}}>{c.estimateDate}{c.estimateTime?" at "+c.estimateTime:""}</div></div></div>}{c.notes&&<div style={{marginTop:4}}><div style={{fontSize:11,fontWeight:700,color:"#586878",marginBottom:6,textTransform:"uppercase"}}>Notes</div><div style={{background:"#1c2a38",borderRadius:10,padding:14,border:"1px solid #2a3a4a",fontSize:13,color:"#8899aa",lineHeight:1.6}}>{c.notes}</div></div>}</div>}
      {c.projectId&&(()=>{const p=PROJECTS.find(x=>x.id===c.projectId);if(!p)return null;return<div style={{marginTop:20,paddingTop:16,borderTop:"1px solid #1e2d3d"}}><div style={{fontSize:11,fontWeight:700,color:"#586878",marginBottom:8,textTransform:"uppercase"}}>Linked Project</div><div style={{background:"#1c2a38",borderRadius:10,padding:14,border:"1px solid #2a3a4a"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:6}}><span style={{fontSize:14,fontWeight:700}}>{p.name}</span><Bg l={p.status} c={stC[p.status]}/></div><div style={{height:4,background:"#23323f",borderRadius:2,overflow:"hidden",marginBottom:6}}><div style={{height:"100%",width:p.progress+"%",borderRadius:2,background:"#22c55e"}}/></div><div style={{display:"flex",gap:14,fontSize:11,color:"#586878"}}><span>✅ {p.tasksDone}/{p.tasks}</span><span>💵 {$(p.spent)}/{$(p.budget)}</span></div></div></div>})()}
    </div>
  </div>);
}

function IntView({ints,si}){
  const toggle=p=>si(v=>v.map(i=>i.provider===p?{...i,connected:!i.connected,acct:!i.connected?"Connected":null}:i));
  return(<div style={{display:"flex",flexDirection:"column",gap:20,maxWidth:700}}>
    <div style={{fontSize:14,color:"#8899aa",lineHeight:1.7}}>Connect payment processors and accounting software. FormUp syncs invoices, payments, and client data automatically.</div>
    {ints.map(ig=><Cd key={ig.provider} style={{padding:0,overflow:"hidden"}}><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:20}}><div style={{display:"flex",alignItems:"center",gap:14}}><div style={{width:48,height:48,borderRadius:12,background:ig.color+"18",display:"flex",alignItems:"center",justifyContent:"center",fontSize:24}}>{ig.icon}</div><div><div style={{fontSize:16,fontWeight:700,display:"flex",alignItems:"center",gap:8}}>{ig.name}{ig.connected&&<span style={{width:8,height:8,borderRadius:4,background:"#22c55e"}}/>}</div><div style={{fontSize:12,color:"#8899aa",marginTop:2}}>{ig.desc}</div>{ig.connected&&ig.acct&&<div style={{fontSize:12,color:"#22c55e",fontWeight:600,marginTop:4}}>✓ {ig.acct}</div>}</div></div><button onClick={()=>toggle(ig.provider)} style={{padding:"10px 20px",borderRadius:10,border:ig.connected?"1px solid #ef444440":"none",background:ig.connected?"transparent":ig.color,color:ig.connected?"#ef4444":"#fff",fontWeight:700,fontSize:13,cursor:"pointer",fontFamily:"inherit"}}>{ig.connected?"Disconnect":"Connect"}</button></div>{ig.connected&&<div style={{borderTop:"1px solid #2a3a4a",padding:"14px 20px",background:"#141d26"}}><div style={{fontSize:12,color:"#8899aa"}}><span style={{fontWeight:600,color:"#e8ecf1"}}>Features: </span>{ig.provider==="stripe"?"Payment links on invoices • Card payments • Auto-reconciliation":ig.provider==="square"?"In-person payments • Online checkout • Payment tracking":"Invoice sync • Expense tracking • Financial reports"}</div></div>}</Cd>)}
    <Cd><div style={{fontSize:14,fontWeight:700,marginBottom:8}}>Manual Payment Links</div><div style={{fontSize:12,color:"#8899aa",marginBottom:12}}>Paste any payment URL (Venmo, PayPal, Zelle) directly on invoices. A "Pay Online" button appears on the PDF.</div></Cd>
  </div>);
}

function InvView(){
  const[prev,setPrev]=useState(null);
  return(<div style={{display:"flex",flexDirection:"column",gap:16}}>
    <div style={{display:"flex",gap:14}}><SB label="Invoiced" value={$(INVOICES.reduce((s,i)=>s+i.amount,0))} icon="📄"/><SB label="Collected" value={$(INVOICES.reduce((s,i)=>s+i.paid,0))} color="#22c55e" icon="✅"/><SB label="Outstanding" value={$(INVOICES.reduce((s,i)=>s+(i.amount-i.paid),0))} color="#f59e0b" icon="⏳"/></div>
    <Cd style={{padding:0,overflow:"hidden"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:13}}><thead><tr style={{borderBottom:"1px solid #2a3a4a"}}>{["Invoice","Project","Client","Amount","Paid","Status","Due",""].map(h=><th key={h} style={{textAlign:"left",padding:"12px 14px",fontSize:10,fontWeight:700,color:"#586878",textTransform:"uppercase"}}>{h}</th>)}</tr></thead><tbody>{INVOICES.map(i=><tr key={i.id} style={{borderBottom:"1px solid #23323f"}} onMouseEnter={e=>e.currentTarget.style.background="#23323f"} onMouseLeave={e=>e.currentTarget.style.background="transparent"}><td style={{padding:"12px 14px",fontWeight:700,fontFamily:"'Space Mono',monospace",fontSize:12}}>{i.id}</td><td style={{padding:"12px 14px",fontWeight:600}}>{i.project}</td><td style={{padding:"12px 14px",color:"#8899aa"}}>{i.client}</td><td style={{padding:"12px 14px",fontWeight:700}}>{$(i.amount)}</td><td style={{padding:"12px 14px",color:i.paid>0?"#22c55e":"#586878",fontWeight:600}}>{$(i.paid)}</td><td style={{padding:"12px 14px"}}><Bg l={i.status} c={invC[i.status]}/></td><td style={{padding:"12px 14px",color:"#586878"}}>{i.dueDate||"—"}</td><td style={{padding:"12px 14px"}}><button onClick={()=>setPrev(i)} style={{padding:"4px 10px",borderRadius:5,border:"1px solid #2a3a4a",background:"transparent",color:"#8899aa",fontSize:11,cursor:"pointer",fontFamily:"inherit"}}>Preview</button></td></tr>)}</tbody></table></Cd>
    {prev&&<div style={{position:"fixed",top:0,left:0,right:0,bottom:0,background:"rgba(0,0,0,.7)",backdropFilter:"blur(4px)",display:"flex",alignItems:"center",justifyContent:"center",zIndex:100}} onClick={()=>setPrev(null)}>
      <div style={{background:"#fff",borderRadius:16,width:680,maxHeight:"90vh",overflow:"auto",color:"#333"}} onClick={e=>e.stopPropagation()}>
        <div style={{background:"#1a1a2e",height:6,borderRadius:"16px 16px 0 0"}}/>
        <div style={{padding:"30px 36px"}}>
          <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:24}}>
            <div style={{display:"flex",alignItems:"center",gap:12}}><img src="/logo.png" alt="Form Up" style={{width:48,height:48,borderRadius:8,objectFit:"cover"}}/><div><div style={{fontSize:22,fontWeight:800,color:"#1a1a2e"}}>Patrick Breen Masonry & Concrete</div><div style={{fontSize:11,color:"#888"}}>South Jersey's Trusted Contractor — 43+ Years</div></div></div>
            <div style={{textAlign:"right"}}><div style={{fontSize:28,fontWeight:800,color:"#1a1a2e",letterSpacing:2}}>INVOICE</div><div style={{fontSize:12,color:"#999",marginTop:4}}>{prev.id} • {prev.date}</div>{prev.dueDate&&<div style={{fontSize:12,color:"#999"}}>Due: {prev.dueDate}</div>}</div>
          </div>
          <div style={{display:"flex",justifyContent:"space-between",padding:20,background:"#f8f9fa",borderRadius:10,marginBottom:20}}>
            <div><div style={{fontSize:10,fontWeight:700,color:"#C41E1E",letterSpacing:1.5,textTransform:"uppercase",borderBottom:"2px solid #C41E1E",paddingBottom:4,marginBottom:8}}>FROM</div><div style={{fontSize:14,fontWeight:700,color:"#1a1a2e"}}>Patrick Breen Masonry & Concrete</div><div style={{fontSize:12,color:"#666"}}>South Jersey, NJ</div></div>
            <div><div style={{fontSize:10,fontWeight:700,color:"#C41E1E",letterSpacing:1.5,textTransform:"uppercase",borderBottom:"2px solid #C41E1E",paddingBottom:4,marginBottom:8}}>BILL TO</div><div style={{fontSize:14,fontWeight:700,color:"#1a1a2e"}}>{prev.client}</div></div>
          </div>
          <table style={{width:"100%",borderCollapse:"collapse",marginBottom:20}}><thead><tr style={{background:"#1a1a2e"}}>{["Description","Qty","Rate","Amount"].map((h,i)=><th key={h} style={{padding:"10px 14px",color:"#fff",fontSize:10,fontWeight:700,textAlign:i>0?"right":"left"}}>{h}</th>)}</tr></thead><tbody><tr><td style={{padding:"12px 14px",borderBottom:"1px solid #e5e5e5"}}>{prev.project}</td><td style={{padding:"12px 14px",borderBottom:"1px solid #e5e5e5",textAlign:"right"}}>1</td><td style={{padding:"12px 14px",borderBottom:"1px solid #e5e5e5",textAlign:"right"}}>{$(prev.amount)}</td><td style={{padding:"12px 14px",borderBottom:"1px solid #e5e5e5",textAlign:"right",fontWeight:600}}>{$(prev.amount)}</td></tr></tbody></table>
          <div style={{display:"flex",justifyContent:"flex-end",marginBottom:24}}><div style={{width:250}}><div style={{display:"flex",justifyContent:"space-between",padding:"6px 0",color:"#666"}}><span>Subtotal</span><span>{$(prev.amount)}</span></div>{prev.paid>0&&<div style={{display:"flex",justifyContent:"space-between",padding:"6px 0",color:"#22c55e"}}><span>Paid</span><span>-{$(prev.paid)}</span></div>}<div style={{display:"flex",justifyContent:"space-between",borderTop:"3px solid #1a1a2e",marginTop:8,paddingTop:12,fontSize:20,fontWeight:800,color:"#1a1a2e"}}><span>BALANCE DUE</span><span>{$(prev.amount-prev.paid)}</span></div></div></div>
          <div style={{textAlign:"center",marginBottom:20}}><a href="#" style={{display:"inline-block",background:"#C41E1E",color:"#fff",padding:"14px 40px",borderRadius:8,textDecoration:"none",fontWeight:700,fontSize:16}}>💳 Pay Online</a><div style={{fontSize:11,color:"#999",marginTop:6}}>Powered by Stripe</div></div>
          <div style={{background:"#f8f9fa",borderRadius:10,padding:16}}><div style={{fontSize:10,fontWeight:700,color:"#999",letterSpacing:1.5,textTransform:"uppercase",marginBottom:8}}>PAYMENT TERMS</div><div style={{fontSize:12,color:"#555",lineHeight:1.7}}>Payment due within 30 days. Thank you for your business!</div></div>
          <div style={{textAlign:"center",marginTop:16,fontSize:11,color:"#aaa"}}>Generated with FormUp</div>
        </div>
        <div style={{padding:"12px 36px 20px",display:"flex",gap:10,justifyContent:"flex-end"}}><button style={{padding:"10px 20px",borderRadius:8,border:"1px solid #ddd",background:"#fff",color:"#333",fontWeight:600,fontSize:13,cursor:"pointer",fontFamily:"inherit"}}>📥 PDF</button><button style={{padding:"10px 20px",borderRadius:8,border:"1px solid #ddd",background:"#fff",color:"#333",fontWeight:600,fontSize:13,cursor:"pointer",fontFamily:"inherit"}}>🖨 Print</button><button style={{padding:"10px 20px",borderRadius:8,border:"none",background:"#C41E1E",color:"#fff",fontWeight:700,fontSize:13,cursor:"pointer",fontFamily:"inherit"}}>📤 Send</button><button onClick={()=>setPrev(null)} style={{padding:"10px 20px",borderRadius:8,border:"1px solid #ddd",background:"#fff",color:"#666",fontWeight:600,fontSize:13,cursor:"pointer",fontFamily:"inherit"}}>Close</button></div>
      </div>
    </div>}
  </div>);
}

function DashView(){
  const ac=PROJECTS.filter(p=>p.status==="active");const rv=INVOICES.reduce((s,i)=>s+i.paid,0);const ot=INVOICES.reduce((s,i)=>s+(i.amount-i.paid),0);const ci=TEAM.filter(t=>t.clockedIn).length;
  return<div style={{display:"flex",flexDirection:"column",gap:20}}>
    <div style={{display:"flex",gap:14,flexWrap:"wrap"}}><SB label="Active Projects" value={ac.length} sub={PROJECTS.filter(p=>p.status==="planning").length+" planning"} color="#f59e0b" icon="📁"/><SB label="Revenue" value={$(rv)} sub="This month" color="#22c55e" icon="💰"/><SB label="Outstanding" value={$(ot)} color="#3b82f6" icon="📄"/><SB label="Crew" value={ci+"/"+TEAM.length} sub="Clocked in" color="#22c55e" icon="👷"/></div>
    <div style={{display:"flex",gap:20}}>
      <div style={{flex:1,display:"flex",flexDirection:"column",gap:20}}>
        <Cd><div style={{fontSize:15,fontWeight:700,marginBottom:14}}>Today's Schedule</div>{SCHEDULE.filter(s=>s.date==="2026-02-23").map(e=><div key={e.id} style={{display:"flex",gap:12,padding:"11px 0",borderBottom:"1px solid #23323f"}}><div style={{width:3,borderRadius:2,background:e.type==="estimate"?"#f59e0b":"#22c55e"}}/><div><div style={{display:"flex",alignItems:"center",gap:6,marginBottom:3}}><span style={{fontSize:12,fontWeight:700,color:e.type==="estimate"?"#f59e0b":"#e8ecf1"}}>{e.time}</span>{e.type==="estimate"&&<span style={{fontSize:9,fontWeight:700,background:"#f59e0b22",color:"#f59e0b",padding:"2px 6px",borderRadius:3,textTransform:"uppercase"}}>Est</span>}</div><div style={{fontSize:13,fontWeight:600}}>{e.project}</div>{e.crew.length>0&&<div style={{fontSize:11,color:"#8899aa",marginTop:2}}>{e.crew.join(", ")}</div>}</div></div>)}</Cd>
        <Cd><div style={{fontSize:15,fontWeight:700,marginBottom:14}}>Activity</div>{ACTIVITY.map(a=><div key={a.id} style={{display:"flex",alignItems:"center",gap:10,padding:"9px 0",borderBottom:"1px solid #23323f"}}><span style={{fontSize:15}}>{a.i}</span><div style={{flex:1,fontSize:12}}><span style={{fontWeight:600}}>{a.a} </span><span style={{color:"#8899aa"}}>{a.b} — {a.c}</span></div><span style={{fontSize:11,color:"#586878"}}>{a.t}</span></div>)}</Cd>
      </div>
      <div style={{width:360,display:"flex",flexDirection:"column",gap:20}}>
        <Cd><div style={{fontSize:15,fontWeight:700,marginBottom:14}}>Active Projects</div>{ac.map(p=><div key={p.id} style={{padding:"12px 0",borderBottom:"1px solid #23323f"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:4}}><span style={{fontSize:13,fontWeight:600}}>{p.name}</span><span style={{fontSize:12,fontWeight:700,color:"#22c55e"}}>{p.progress}%</span></div><div style={{fontSize:11,color:"#8899aa",marginBottom:6}}>{p.address}</div><div style={{height:3,background:"#23323f",borderRadius:2}}><div style={{height:"100%",width:p.progress+"%",borderRadius:2,background:p.progress>80?"#22c55e":"#3b82f6"}}/></div></div>)}</Cd>
        <Cd><div style={{fontSize:15,fontWeight:700,marginBottom:14}}>Integrations</div>{INTEGRATIONS_INIT.map(ig=><div key={ig.provider} style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"8px 0",borderBottom:"1px solid #23323f"}}><div style={{display:"flex",alignItems:"center",gap:8}}><span style={{fontSize:16}}>{ig.icon}</span><span style={{fontSize:13,fontWeight:600}}>{ig.name}</span></div>{ig.connected?<span style={{fontSize:11,fontWeight:700,color:"#22c55e"}}>● Connected</span>:<span style={{fontSize:11,color:"#586878"}}>Not connected</span>}</div>)}</Cd>
      </div>
    </div>
  </div>;
}

function ProjView(){const[f,setF]=useState("all");const[sel,setSel]=useState(null);const ls=f==="all"?PROJECTS:PROJECTS.filter(p=>p.status===f);return<div style={{display:"flex",flexDirection:"column",gap:16}}><div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{["all","active","planning","completed"].map(s=><Pl key={s} a={f===s} onClick={()=>setF(s)} l={(s==="all"?"All":s[0].toUpperCase()+s.slice(1))+" ("+(s==="all"?PROJECTS.length:PROJECTS.filter(p=>p.status===s).length)+")"} c={stC[s]}/>)}</div>{ls.map(p=><Cd key={p.id} hover style={{cursor:"pointer",padding:16,borderColor:sel===p.id?"#c41e1e":undefined}} onClick={()=>setSel(sel===p.id?null:p.id)}><div style={{display:"flex",justifyContent:"space-between",marginBottom:6}}><div style={{display:"flex",alignItems:"center",gap:8}}><div style={{width:8,height:8,borderRadius:4,background:stC[p.status]||"#586878"}}/><span style={{fontSize:15,fontWeight:700}}>{p.name}</span></div><Bg l={p.status} c={stC[p.status]||"#586878"}/></div><div style={{fontSize:12,color:"#8899aa"}}>{p.client} • {p.address}</div>{sel===p.id&&<div style={{marginTop:14,paddingTop:14,borderTop:"1px solid #23323f"}}><div style={{display:"flex",gap:20,flexWrap:"wrap",marginBottom:12}}>{[{l:"Budget",v:$(p.budget)},{l:"Spent",v:$(p.spent)},{l:"Tasks",v:p.tasksDone+"/"+p.tasks}].map(s=><div key={s.l}><div style={{fontSize:10,color:"#586878"}}>{s.l}</div><div style={{fontSize:17,fontWeight:800}}>{s.v}</div></div>)}</div><div style={{height:5,background:"#23323f",borderRadius:3}}><div style={{height:"100%",width:p.progress+"%",borderRadius:3,background:"#22c55e"}}/></div>{p.crew.length>0&&<div style={{display:"flex",gap:6,marginTop:10}}>{p.crew.map((c,i)=><span key={i} style={{fontSize:11,fontWeight:600,background:"#23323f",color:"#8899aa",padding:"3px 8px",borderRadius:5}}>{c}</span>)}</div>}</div>}</Cd>)}</div>}

function SchedView(){const ds=["2026-02-23","2026-02-24","2026-02-25"],lb=["Mon, Feb 23","Tue, Feb 24","Wed, Feb 25"];return<div style={{display:"flex",flexDirection:"column",gap:16}}><div style={{display:"flex",justifyContent:"space-between"}}><span style={{fontSize:15,fontWeight:700}}>Week of February 23</span></div><div style={{display:"flex",gap:14}}>{ds.map((d,i)=><div key={d} style={{flex:1}}><div style={{fontSize:13,fontWeight:700,color:i===0?"#e63939":"#8899aa",marginBottom:10,paddingBottom:6,borderBottom:"2px solid "+(i===0?"#c41e1e":"#23323f")}}>{lb[i]}{i===0&&<span style={{fontSize:10,color:"#c41e1e",marginLeft:6}}>TODAY</span>}</div><div style={{display:"flex",flexDirection:"column",gap:8}}>{SCHEDULE.filter(s=>s.date===d).map(e=><Cd key={e.id} hover style={{padding:12,borderLeft:"3px solid "+(e.type==="estimate"?"#f59e0b":"#22c55e")}}><div style={{fontSize:11,fontWeight:700,color:e.type==="estimate"?"#f59e0b":"#22c55e",marginBottom:3}}>{e.time}</div><div style={{fontSize:13,fontWeight:600,marginBottom:2}}>{e.project}</div>{e.crew.length>0&&<div style={{fontSize:11,color:"#8899aa"}}>{e.crew.join(", ")}</div>}{e.notes&&<div style={{fontSize:11,color:"#586878",marginTop:3}}>{e.notes}</div>}</Cd>)}</div></div>)}</div></div>}

function HrsView(){return<div style={{display:"flex",flexDirection:"column",gap:16}}><div style={{display:"flex",gap:14}}><SB label="Today" value={TEAM.reduce((s,t)=>s+t.todayHours,0).toFixed(1)+"h"} color="#22c55e" icon="⏰"/><SB label="Week" value={TEAM.reduce((s,t)=>s+t.weekHours,0).toFixed(0)+"h"} color="#3b82f6" icon="📊"/></div><Cd><div style={{fontSize:15,fontWeight:700,marginBottom:14}}>Employee Hours</div>{TEAM.map(t=><div key={t.id} style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"11px 0",borderBottom:"1px solid #23323f"}}><div style={{display:"flex",alignItems:"center",gap:10}}><div style={{width:32,height:32,borderRadius:8,background:t.clockedIn?"#22c55e22":"#23323f",border:"1.5px solid "+(t.clockedIn?"#22c55e":"#2a3a4a"),display:"flex",alignItems:"center",justifyContent:"center",fontSize:11,fontWeight:700,color:t.clockedIn?"#22c55e":"#586878"}}>{t.avatar}</div><div><div style={{fontSize:13,fontWeight:600,display:"flex",alignItems:"center",gap:6}}>{t.name}{t.clockedIn&&<span style={{width:6,height:6,borderRadius:3,background:"#22c55e"}}/>}</div><div style={{fontSize:11,color:"#586878",textTransform:"capitalize"}}>{t.role}</div></div></div><div style={{display:"flex",gap:24,alignItems:"center"}}><div style={{textAlign:"center"}}><div style={{fontSize:10,color:"#586878"}}>Today</div><div style={{fontSize:14,fontWeight:700}}>{t.todayHours}h</div></div><div style={{textAlign:"center"}}><div style={{fontSize:10,color:"#586878"}}>Week</div><div style={{fontSize:14,fontWeight:700,color:t.weekHours>40?"#ef4444":"#e8ecf1"}}>{t.weekHours}h</div></div><div style={{width:80}}><div style={{height:5,background:"#23323f",borderRadius:3}}><div style={{height:"100%",borderRadius:3,width:Math.min(100,(t.weekHours/40)*100)+"%",background:t.weekHours>40?"#ef4444":"#22c55e"}}/></div></div></div></div>)}</Cd><Cd style={{padding:0,overflow:"hidden"}}><div style={{padding:"14px 14px 0",fontSize:15,fontWeight:700}}>Recent Entries</div><table style={{width:"100%",borderCollapse:"collapse",fontSize:12,marginTop:10}}><thead><tr style={{borderBottom:"1px solid #2a3a4a"}}>{["Employee","Date","In","Out","Hours","Project"].map(h=><th key={h} style={{textAlign:"left",padding:"9px 14px",fontSize:10,fontWeight:700,color:"#586878",textTransform:"uppercase"}}>{h}</th>)}</tr></thead><tbody>{TIME_ENTRIES.map(e=><tr key={e.id} style={{borderBottom:"1px solid #23323f"}}><td style={{padding:"9px 14px",fontWeight:600}}>{e.emp}</td><td style={{padding:"9px 14px",color:"#8899aa"}}>{e.date}</td><td style={{padding:"9px 14px",fontFamily:"'Space Mono'",fontSize:11}}>{e.ci}</td><td style={{padding:"9px 14px",fontFamily:"'Space Mono'",fontSize:11,color:e.co?"#e8ecf1":"#22c55e"}}>{e.co||"Active"}</td><td style={{padding:"9px 14px",fontWeight:700}}>{e.hrs}h</td><td style={{padding:"9px 14px"}}>{e.proj}</td></tr>)}</tbody></table></Cd></div>}

function EqView(){return<div style={{display:"flex",flexDirection:"column",gap:16}}><div style={{display:"flex",gap:14}}><SB label="Available" value={EQUIPMENT.filter(e=>e.status==="available").length} color="#22c55e" icon="✅"/><SB label="Checked Out" value={EQUIPMENT.filter(e=>e.status==="checked_out").length} color="#f59e0b" icon="🔧"/><SB label="Maintenance" value={EQUIPMENT.filter(e=>e.status==="maintenance").length} color="#ef4444" icon="⚠️"/></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(300px,1fr))",gap:10}}>{EQUIPMENT.map(eq=><Cd key={eq.id} hover style={{padding:14}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:6}}><div><div style={{fontSize:14,fontWeight:700}}>{eq.name}</div><div style={{fontSize:11,color:"#586878",fontFamily:"'Space Mono'"}}>{eq.serial}</div></div><Bg l={eq.status.replace("_"," ")} c={eqC[eq.status]}/></div>{eq.project&&<div style={{fontSize:12,color:"#8899aa",marginTop:4}}>📁 {eq.project}</div>}{eq.checkedBy&&<div style={{fontSize:11,color:"#586878",marginTop:2}}>👤 {eq.checkedBy}</div>}</Cd>)}</div></div>}

function TeamView(){return<div style={{display:"flex",flexDirection:"column",gap:16}}><div style={{display:"flex",gap:14}}><SB label="Team" value={TEAM.length} icon="👥"/><SB label="On Site" value={TEAM.filter(t=>t.clockedIn).length} color="#22c55e" icon="📍"/></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(320px,1fr))",gap:12}}>{TEAM.map(t=><Cd key={t.id} hover style={{padding:16}}><div style={{display:"flex",alignItems:"center",gap:12,marginBottom:12}}><div style={{width:44,height:44,borderRadius:12,background:"linear-gradient(135deg,"+(t.clockedIn?"#22c55e":"#2a3a4a")+","+(t.clockedIn?"#16a34a":"#1c2a38")+")",display:"flex",alignItems:"center",justifyContent:"center",fontSize:15,fontWeight:700,color:"#fff"}}>{t.avatar}</div><div><div style={{fontSize:15,fontWeight:700,display:"flex",alignItems:"center",gap:6}}>{t.name}{t.clockedIn&&<span style={{width:7,height:7,borderRadius:4,background:"#22c55e"}}/>}</div><div style={{fontSize:12,color:"#586878",textTransform:"capitalize"}}>{t.role}</div></div></div><div style={{fontSize:12,color:"#8899aa"}}>📧 {t.email}</div><div style={{fontSize:12,color:"#8899aa",marginTop:2}}>📞 {t.phone}</div><div style={{display:"flex",gap:16,marginTop:12,paddingTop:10,borderTop:"1px solid #23323f"}}><div><div style={{fontSize:10,color:"#586878"}}>Today</div><div style={{fontSize:15,fontWeight:700}}>{t.todayHours}h</div></div><div><div style={{fontSize:10,color:"#586878"}}>Week</div><div style={{fontSize:15,fontWeight:700,color:t.weekHours>40?"#ef4444":"#e8ecf1"}}>{t.weekHours}h</div></div></div></Cd>)}</div></div>}
